# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Interest.destroy_all
Item.destroy_all
Favorite.destroy_all

user1 = User.create(username: "mrs161", name: "Madeline Stalter", location: "Brooklyn, New York", profile_pic: "https://lh3.googleusercontent.com/proxy/d4NagMGHOQ3arQR6elqtzaEJl4LMdbaz9wRF8NSnA2RehMyR3nZRLTgeZdF-Z4Kia58dINRlfhRgAbq2AsheCjA32FZmdfKjLpaH1IcA0HcOJ6GYC2GUzxsh8JW99JL42CSL44Ru1M3JObw71h55S-lk4xiETH-IiIek")
# user2 = User.create(username: "jg71", name: "Johnnie Gonzalez", location: "Elizabeth, New Jersey", profile_pic: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/DOG-HUSKY_23JUL00.jpg/220px-DOG-HUSKY_23JUL00.jpg")
# user3 = User.create(username: "eaf40", name: "Erik Frost", location: "Brooklyn, New York", profile_pic: "https://lmegj1zls2x46spge37mwjqd-wpengine.netdna-ssl.com/wp-content/uploads/image4-1.png")

interest1 = Interest.create(category: "Architecture & Design", avatar: "https://cdn.rit.edu/images/news/2018-12/architecture.jpg")
interest2 = Interest.create(category: "Travel", avatar: "https://www.ksat.com/resizer/i3ZhVJv2ykedu5JQdNjmADieJvo=/1280x1024/smart/filters:format(jpeg):strip_exif(true):strip_icc(true):no_upscale(true):quality(65)/cloudfront-us-east-1.images.arcpublishing.com/gmg/GALRBVCXFBGV3FVVUFXOMOZCDA.jpg")
interest3 = Interest.create(category: "Green Sustainability", avatar: "https://en.nhandan.com.vn/cdn/en/media/k2/items/src/727/06b6741b1354675dc998415c94fb0e60.jpg")
interest4 = Interest.create(category: "True Crime", avatar: "https://images2.minutemediacdn.com/image/upload/c_fill,g_auto,h_1248,w_2220/f_auto,q_auto,w_1100/v1555288890/shape/mentalfloss/istock-495760198.jpg")
interest5 = Interest.create(category: "Sports", avatar: "https://sport.one/content/images/2018/01/2222-18.jpg")
interest6 = Interest.create(category: "Tech", avatar: "https://inteng-storage.s3.amazonaws.com/img/iea/nR6bkXZxwo/sizes/software-engineering-skills_md.jpg")

# Architecture & Design
item1 = Item.create(interest_id: interest1.id, title: "Gothic", description: "Gothic architecture is a European style of architecture that values height and exhibits an intricate and delicate aesthetic. Though its roots are French, the Gothic approach can be found in churches, cathedrals, and other similar buildings in Europe and beyond.", card_image: "https://mymodernmet.com/wp/wp-content/uploads/2017/11/gothic-architecture-characteristics-1.jpg")
item2 = Item.create(interest_id: interest1.id, title: "Modern", description: "Modern architecture is an architectural style based upon new and innovative technologies of construction, particularly the use of glass, steel, and reinforced concrete; based upon the idea that form should follow function, embrace of minimalism, and reject the ornament.", card_image: "https://i.pinimg.com/564x/99/4f/35/994f3504ba7a79d6eb0c6d7049222946.jpg")
item3 = Item.create(interest_id: interest1.id, title: "Neoclassical", description: "Neoclassical architecture is characterized by grandeur of scale, simplicity of geometric forms, Greek (particularly Doric) and Roman detail, dramatic use of columns, and a preference for blank walls.", card_image: "https://www.thoughtco.com/thmb/rrjfYeRPXnwM9LxX3vhW6c0tIsM=/4965x2793/smart/filters:no_upscale()/architecture-neoclassic-capitol-643699604-crop-5ad565a831283400364a32d0.jpg")
# Travel
item4 = Item.create(interest_id: interest2.id, title: "Zermatt, Switzerland", description: "Located in southern Switzerland’s Valais canton, Zermatt is a mountain resort renowned for skiing, climbing, and hiking. The town, at an elevation of around 1,600m, lies below the iconic Matterhorn peak. Its main street, Bahnhofstrasse is lined with boutique shops, hotels and restaurants, and also has a lively après-ski scene.", card_image: "https://s27363.pcdn.co/wp-content/uploads/2019/12/Zermatt-for-Facebook.jpg.optimal.jpg")
item5 = Item.create(interest_id: interest2.id, title: "Munich, Germany", description: "Munich, Bavaria’s capital, is home to centuries-old buildings and numerous museums. The city is known for its annual Oktoberfest celebration and its beer halls, including the famed Hofbräuhaus that was founded in 1589. In the Altstadt (Old Town), central Marienplatz square contains landmarks such as Neo-Gothic Neues Rathaus (town hall), with a popular glockenspiel show that chimes and reenacts stories from the 16th century.", card_image: "https://s.abcnews.com/images/Lifestyle/munich-gty-jpo-170915_16x9_1600.jpg")
item6 = Item.create(interest_id: interest2.id, title: "Tokoyo, Japan", description: "Tokyo, Japan’s busy capital, mixes the ultramodern and the traditional, from neon-lit skyscrapers to historic temples. The opulent Meiji Shinto Shrine is known for its towering gate and surrounding woods. The Imperial Palace sits amid large public gardens. The city's many museums offer exhibits ranging from classical art (in the Tokyo National Museum) to a reconstructed kabuki theater (in the Edo-Tokyo Museum).", card_image: "https://i.insider.com/5d26280921a86107bb51bd92?width=1067&format=jpeg")
# Green Sustainability
item7 = Item.create(interest_id: interest3.id, title: "Bamboo Toothbrush", description: "The greatest eco-friendly benefit of the bamboo toothbrush is the material used. The bamboo handle is entirely degradable and the nylon-4 bristles degrade in less time than the nylon-6 material used in plastic toothbrushes. Plastic toothbrushes not only take a lot of energy/resources to create; they also release harmful toxins into the environment. Plastic toothbrushes are essentially non-biodegradable as they take a millennium to degrade.", card_image: "https://parkcrestdental.com/wp-content/uploads/2018/06/Bamboo-toothbrushes.jpg")
item8 = Item.create(interest_id: interest3.id, title: "Toothpaste Bites", description: "Skip the plastic containers that take a millennium to degrade all while releasing harmful toxins into the environment! Place one toothpaste bite in your mouth, bite down, and brush with a wet bamboo toothbrush.", card_image: "https://cdn.shopify.com/s/files/1/1864/2187/files/20.08.09---Mint-subscription-pdp-1.jpg?v=1597088179")
item9 = Item.create(interest_id: interest3.id, title: "Reusable Makeup Remover Wipe", description: "Invest in a microfiber towel or washable round to cut back on landfill waste caused by disposable cotton rounds and makeup wipes. Not to mention, the reusable cloth provides a deeper clean and is softer on the skin thus avoiding damage/micro-tears! ", card_image: "https://media.glamour.com/photos/5ea0773c089e1800082ffcbd/master/w_400%2Cc_limit/blooming%2520bee.jpg")
# True Crime
item10 = Item.create(interest_id: interest4.id, title: "Ted Bundy", description: "Theodore Robert Bundy was an American serial killer that was active between 1974 and 1978. Before his execution, after a decade of denial, he admitted to raping and killing 30 women across 7 state lines. However, the true number of victims remains unknown.", card_image: "https://i.insider.com/5c5c4b24eb3ce8380314b434?width=750&format=jpeg&auto=webp")
item11 = Item.create(interest_id: interest4.id, title: "Jeffrey Dahmer", description: "Jeffrey Dahmer, better known as the Milwaukee Cannibal, was an American serial killer that murdered and dismembered 17 young men from 1978 to 1991. Many of his later murders involved necrophilia, cannibalism, and the permanent preservation of body parts.", card_image: "https://www.biography.com/.image/c_fit%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_620/MTYxMzc0NzEzNjAyMzg1ODMy/jeffrey-dahmer-mug--photo-by-curt-borgwardtsygma-via-getty-images.jpg")
item12 = Item.create(interest_id: interest4.id, title: "Zodiac Killer", description: "Zodiac Killer is the pseudonym of an American serial killer who operated in Northern California from the late 1960s to the early 1970s. His identity remains unknown. The killer originated the name in a series of taunting letters sent to the San Francisco Bay Area press. The Zodiac Killer claimed to have murdered 37 individuals; 5 are confirmed and 2 victims survived an attack", card_image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Zodiac-Killer.jpg")
# Sports
item13 = Item.create(interest_id: interest5.id, title: "Football", description: "Antonio Brown is back in the NFL and set to make his return in Week 9 as part of the Tampa Bay Buccaneers.", card_image: "https://cdn.vox-cdn.com/thumbor/ZFT6wXMJMKJLxhri-2oHhNHEAHA=/0x0:4858x3239/1200x800/filters:focal(2229x572:3005x1348)/cdn.vox-cdn.com/uploads/chorus_image/image/67739125/201104_KZ_Practice_0014.0.jpg")
item14 = Item.create(interest_id: interest5.id, title: "Hockey", description: "Ahead of the start of Day Two of the NHL Draft, the Pittsburgh Penguins traded two-time Stanely Cup champion, Matthew Murray, to the Ottawa Senators for forward prospect Jonathan Gruden and a 2020 second-round pick. This trade that will ultimately give Pittsburgh more cap relief for next season.", card_image: "https://images2.minutemediacdn.com/image/fetch/w_736,h_485,c_fill,g_auto,f_auto/https%3A%2F%2Fsenshot.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2017%2F07%2F1186220066-850x560.jpeg")
item15 = Item.create(interest_id: interest5.id, title: "Skiing", description: "How will the corona virus change the 2020-2021 ski season? The car becomes the lodge, due to reduced indoor capacities; grab-and-go will be encouraged for dining; and expect longer lift lines as less people are allowed on the gondola/chair at one time. Being flexible is key - be grateful you're healthy enough to ski!", card_image: "https://www.iii.org/insuranceindustryblog/wp-content/uploads/2019/01/iStock-999962446.jpg")
# Tech
item16 = Item.create(interest_id: interest6.id, title: "JavaScript", description: "Vanilla JavaScript was the death of me; but my ghost is a lot smarter.", card_image: "https://static.frontendmasters.com/assets/courses/2019-04-05-js-recent-parts/thumb@2x.jpg")
item17 = Item.create(interest_id: interest6.id, title: "React", description: "The BEST framework, duh!", card_image: "https://reactjs.org/logo-og.png")
item18 = Item.create(interest_id: interest6.id, title: "Rails", description: "The back end can be a scary, but fun, place.", card_image: "https://cdn.sanity.io/images/ay6gmb6r/production/bb652b4b35320ed08b3ed63eeea9f97446776296-2240x1260.png")

favorite1 = Favorite.create(user_id: user1.id, interest_id: interest1.id)
# favorite2 = Favorite.create(user_id: user1.id, interest_id: interest2.id)
# favorite3 = Favorite.create(user_id: user1.id, interest_id: interest3.id)
# favorite4 = Favorite.create(user_id: user1.id, interest_id: interest4.id)
# favorite5 = Favorite.create(user_id: user1.id, interest_id: interest5.id)
# favorite3 = Favorite.create(user_id: user1.id, interest_id: interest6.id)

